import './css/style.css'

import { Inter, Architects_Daughter } from 'next/font/google'

import NavBar from '@/components/ui/nav-bar'
import Providers from '@/components/ui/Providers'
import  { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'



const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased  text-gray-200 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden">
          {/* <NavBar session={session}/> */}
          <Providers> {children}</Providers>
        </div>
      </body>
    </html>
  )
}
 